export const TEST_IDS = {
  // Components
  COMPONENT_NAVBAR: "COMPONENT_NAVBAR",
  COMPONENT_NAVBAR_HOME_BUTTON: "COMPONENT_NAVBAR_HOME_BUTTON",
  COMPONENT_NAVBAR_COMPARISON_BUTTON: "COMPONENT_NAVBAR_COMPARISON_BUTTON",
  COMPONENT_NAVBAR_AGENT_BUTTON: "COMPONENT_NAVBAR_AGENT_BUTTON",

  // Containers
  // HOME
  CONTAINER_HOME_ROOT: "CONTAINER_HOME_ROOT",

  // COMPARISON
  CONTAINER_COMPARISON_ROOT: "CONTAINER_COMPARISON_ROOT",

  // AGENT
  CONTAINER_AGENT_ROOT: "CONTAINER_AGENT_ROOT",

  // NOT FOUND
  CONTAINER_NOT_FOUND_ROOT: "CONTAINER_NOT_FOUND_ROOT"
};
